@BASE_URL = http://localhost:3001/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpdmVPbmVzIiwiaWQiOiI2NGQ0OTU2MjhmM2E2OGZkYzQ1ZTVmZmYiLCJpYXQiOjE2OTI0MjgzNzksImV4cCI6MTY5MzAzMzE3OX0.mUSsYH89dnogxCJo07Zl2uT4rIpI_T0vsxrJEbGl6mc
@ID = 64e06a7fada1e353c7381f1a

# ABTS1000
@COURSE_ID = 64df62004cb4f7752ad4d280 
@COMMENT_ID = 64e06bb0fe4c2b958ae3f17e

### GET all course reviews
GET {{BASE_URL}}/courseReviews

### GET a specific course review.
GET {{BASE_URL}}/courseReviews/{{ID}}

### CREATE a new course review.
POST {{BASE_URL}}/courseReviews
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Introduction to Computer Science",
  "content": "This course was a great introduction to the field of computer science. The professor was knowledgeable and engaging, and the workload was manageable.",
  "semester": "Fall 2021",
  "professor": "Dr. Smith",
  "date": "2021-10-01T00:00:00.000Z",
  "rating": 4,
  "difficulty": 3,
  "lectureQuality": 4,
  "tutorialQuality": 3,
  "workload": 3,
  "likes": [],
  "dislikes": [],
  "reports": [],
  "pros": ["Engaging professor", "Interesting material"],
  "cons": ["Some assignments were unclear"],
  "comments": [],
  "course": "64df62004cb4f7752ad4d280"
}

### UPDATE a course review
PUT {{BASE_URL}}/courseReviews/{{ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Introduction to Computer Science",
  "content": "ACTUALLY, this wasn't a good course",
  "semester": "Fall 2021",
  "professor": "Dr. Smith",
  "date": "2021-10-01T00:00:00.000Z",
  "rating": 4,
  "difficulty": 3,
  "lectureQuality": 4,
  "tutorialQuality": 3,
  "workload": 3,
  "likes": [],
  "dislikes": [],
  "reports": [],
  "pros": ["Engaging professor", "Interesting material"],
  "cons": ["Some assignments were unclear"],
  "course": "64df62004cb4f7752ad4d280"
}

### DELETE a course review.
DELETE {{BASE_URL}}/courseReviews/{{ID}}
Authorization: Bearer {{TOKEN}}

### GET all the comments in a course review.
GET {{BASE_URL}}/courseReviews/{{ID}}/comments

### POST a new comment to a course review.
POST {{BASE_URL}}/courseReviews/{{ID}}/comments
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "content": "I really agree with this review.",
  "date": "2021-10-01T00:00:00.000Z",
  "likes:": [],
  "dislikes:": [],
  "reports": []
}

### UPDATE a comment in a course review.
PUT {{BASE_URL}}/courseReviews/{{ID}}/comments/{{COMMENT_ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "content": "I REALLY DISAGREE agree with this review.",
  "date": "2021-10-01T00:00:00.000Z",
  "likes:": [],
  "dislikes:": [],
  "reports": []
}

### DELETE a comment from a course review.
DELETE {{BASE_URL}}/courseReviews/{{ID}}/comments/{{COMMENT_ID}}
Authorization: Bearer {{TOKEN}}