@BASE_URL = http://localhost:3001/api
@ID = 64d472dd5dd883cfffd5de3f
### Get a list of all courses
GET {{BASE_URL}}/courses

### Get a single course
GET {{BASE_URL}}/courses/{{ID}}

### Create a course
POST {{BASE_URL}}/courses
Content-Type: application/json

{
  "code": "CSSE1001",
  "title": "Introduction to Computer Science",
  "url": "https://example.com/courses/cs101",
  "faculty": "Computer Science Department",
  "professor": "John Doe",
  "avgRating": 4.5,
  "units": 2
}

### Update a course
PUT {{BASE_URL}}/courses/{{ID}}
Content-Type: application/json

{
  "code": "CSSE1001",
  "title": "Introduction to Computer Science",
  "url": "https://example.com/courses/cs101",
  "faculty": "Computer Science Department",
  "professor": "John Doe",
  "avgRating": 4.0,
  "units": 2
}

### Delete a course
DELETE {{BASE_URL}}/courses/{{ID}}

### Get a list of all the course's reviews
GET {{BASE_URL}}/courses/{{ID}}/reviews
