@BASE_URL = http://localhost:3001/api
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpdmVPbmVzIiwiaWQiOiI2NGQ0OTU2MjhmM2E2OGZkYzQ1ZTVmZmYiLCJpYXQiOjE2OTE2NTQ3MTMsImV4cCI6MTY5MjI1OTUxM30.x5oIEJd3s5f64Zajopwhc8U-A7TRkuDNpGa5qP9u7Ao
@ID = 64d49cece8cf46b1a9f49ece

### GET all course reviews
GET {{BASE_URL}}/courseReviews

### GET a specific course review.
GET {{BASE_URL}}/courseReviews/{{ID}}

### CREATE a new course review.
POST {{BASE_URL}}/courseReviews
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Introduction to Computer Science Review",
  "content": "I thoroughly enjoyed this course.",
  "semester": "Fall 2023",
  "professor": "Professor Snape",
  "date": "2023-08-10T12:34:56Z",
  "rating": 4.5,
  "difficulty": 3,
  "lectureQuality": 4,
  "tutorialQuality": 3,
  "workload": 2,
  "likes": 15,
  "dislikes": 2,
  "reports": 0,
  "pros": ["Engaging lectures", "Helpful resources"],
  "cons": ["Heavy workload"],
  "course": "64d472dd5dd883cfffd5de3f"
}

### UPDATE a course review
PUT {{BASE_URL}}/courseReviews/{{ID}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Introduction to Computer Science Review",
  "content": "Actually, I didn't enjoy this course...",
  "semester": "Fall 2023",
  "professor": "Professor Snape",
  "date": "2023-08-10T12:34:56Z",
  "rating": 4.0,
  "difficulty": 3,
  "lectureQuality": 4,
  "tutorialQuality": 3,
  "workload": 2,
  "likes": 15,
  "dislikes": 2,
  "reports": 0,
  "pros": ["Engaging lectures", "Helpful resources"],
  "cons": ["Heavy workload"],
  "course": "64d472dd5dd883cfffd5de3f"
}

### DELETE a course review.
DELETE {{BASE_URL}}/courseReviews/{{ID}}
Authorization: Bearer {{TOKEN}}
