@BASE_URL = http://localhost:3001/api
@ID = 64d2f452f33cc6882ae39ff0

### Get a list of all professors
GET {{BASE_URL}}/professors

### Make a single professor
POST {{BASE_URL}}/professors
Content-Type: application/json

{
  "name": "Professor Snape",
  "faculty": "Potions",
  "avgRating": "70.8"
}

### Delete a single professor
DELETE {{BASE_URL}}/professors/{{ID}}
