@base_url = http://localhost:3001/api
### Get a list of all users
GET {{base_url}}/users

### GET a single user
GET http://localhost:3001/api/users/64d495628f3a68fdc45e5fff

### Make a single user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "fiveOnes",
  "email": "fiveOnes@gmail.com",
  "name": "five_ones",
  "password": "11111"
}

### Update a single user and resets reviews. CAN ALSO UPDATE REVIEWS
PUT http://localhost:3001/api/users/64d495628f3a68fdc45e5fff
Content-Type: application/json

{
  "username": "fiveOnes",
  "email": "fiveOnes@gmail.com",
  "name": "five_ones",
  "courseReviews": [],
}

### Login with valid user
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "fiveOnes",
  "password": "11111"
}

### Login with invalid user
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "fiveOnes",
  "password": "1111"
}

### Delete a single user
DELETE http://localhost:3001/api/users/64d495628f3a68fdc45e5fff

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpdmVPbmVzIiwiaWQiOiI2NGQ0OTU2MjhmM2E2OGZkYzQ1ZTVmZmYiLCJpYXQiOjE2OTE2NTQ3MTMsImV4cCI6MTY5MjI1OTUxM30.x5oIEJd3s5f64Zajopwhc8U-A7TRkuDNpGa5qP9u7Ao